// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Entities
{
    // Address
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class AddressModel
    {
        public int ClientId { get; set; } // ClientID (Primary key)
        public string Country { get; set; } // Country (length: 50)
        public string State { get; set; } // State (length: 50)
        public string City { get; set; } // City (length: 50)
        public string Address_ { get; set; } // Address (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Client pointed by [Addresses].([ClientId]) (FK_ClientAddress)
        /// </summary>
        public virtual ClientModel ClientModel { get; set; } // FK_ClientAddress
    }

}
// </auto-generated>
