// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Entities
{

    // Operations
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class OperationModel
    {
        public int OperationId { get; set; } // OperationID (Primary key)
        public string OutId { get; set; } // OutID (length: 16)
        public string InId { get; set; } // InID (length: 16)
        public decimal Amount { get; set; } // Amount
        public decimal OutBalanceAfter { get; set; } // OutBalanceAfter
        public decimal InBalanceAfter { get; set; } // InBalanceAfter
        public System.DateTime OperationTime { get; set; } // OperationTime

        // Foreign keys

        /// <summary>
        /// Parent Card pointed by [Operations].([InId]) (FK_InCard)
        /// </summary>
        public virtual CardModel In { get; set; } // FK_InCard

        /// <summary>
        /// Parent Card pointed by [Operations].([OutId]) (FK_OutCard)
        /// </summary>
        public virtual CardModel Out { get; set; } // FK_OutCard

        public OperationModel()
        {
            OperationTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
